### ISSUE TITLE
Compilation errors on MacOS High Sierra

### ISSUE THREAD

**Issue by iref-use** [orbisdev/ps4sh#2]
Sorry, I don't have much experience in C.
Try to compile ps4sh and getting some errors.
Tried to use clang as a compiler, but I get the same thing.
![screen shot 2019-01-10 at 1 02 18 pm](https://user-images.githubusercontent.com/35736557/50961231-38cd9780-14d8-11e9-89e2-de69c00e5c55.png)

**Comment by j4ckp0t85** [comment]
i have faced this error too. it is caused by a bad behaviour on mac os (used libedit instead of readline).

use my fork version and you should be fine.

**Comment by iref-use** [comment]
@j4ckp0t85 Thank you. Build it.
but I had to make some changes in Makefile:
`-L/opt/local/lib -lpthread -lcurses -lncurses`
change to
`-L/usr/lib -lpthread -lcurses -lncurses`

**Comment by j4ckp0t85** [comment]
maybe i have symlinked (brew link) i don't remember to be honest.

i will add to my readme
